version: '3.8'

networks:
  zabbix-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
          ip_range: 172.20.240.0/20

volumes:
  dbzpgsql:
  zabbix-snmptraps:

services:
  postgres-server:
    image: postgres:latest
    container_name: postgres-server
    environment:
      POSTGRES_USER: "zxmtsys"
      POSTGRES_PASSWORD: "1zDkKOq78w"
      POSTGRES_DB: "zxdb"
    volumes:
      - dbzpgsql:/var/lib/postgresql/data
    networks:
      zabbix-network:
        ipv4_address: 172.20.240.5
    restart: unless-stopped

  zabbix-snmptraps:
    image: zabbix/zabbix-snmptraps:alpine-7.4-latest
    container_name: zabbix-snmptraps
    volumes:
      - zabbix-snmptraps:/var/lib/zabbix/snmptraps:rw
      - /var/lib/zabbix/mibs:/usr/share/snmp/mibs:ro
    networks:
      zabbix-network:
        ipv4_address: 172.20.240.6
    ports:
      - "162:1162/udp"
    restart: unless-stopped

  zabbix-server-pgsql:
    image: zabbix/zabbix-server-pgsql:alpine-7.4-latest
    container_name: zabbix-server-pgsql
    environment:
      DB_SERVER_HOST: "postgres-server"
      POSTGRES_USER: "zxmtsys"
      POSTGRES_PASSWORD: "1zDkKOq78w"
      POSTGRES_DB: "zxdb"
      ZBX_ENABLE_SNMP_TRAPS: "true"
    volumes:
      - zabbix-snmptraps:/var/lib/zabbix/snmptraps
    networks:
      zabbix-network:
        ipv4_address: 172.20.240.7
    ports:
      - "10051:10051"
    depends_on:
      - postgres-server
      - zabbix-snmptraps
    restart: unless-stopped

  zabbix-web-nginx-pgsql:
    image: zabbix/zabbix-web-nginx-pgsql:alpine-7.4-latest
    container_name: zabbix-web-nginx-pgsql
    environment:
      ZBX_SERVER_HOST: "zabbix-server-pgsql"
      DB_SERVER_HOST: "postgres-server"
      POSTGRES_USER: "zxmtsys"
      POSTGRES_PASSWORD: "1zDkKOq78w"
      POSTGRES_DB: "zxdb"
    volumes:
      - /etc/ssl/nginx:/etc/ssl/nginx:ro
    networks:
      zabbix-network:
        ipv4_address: 172.20.240.8
    ports:
      - "80:8080"
      - "443:8443"
    depends_on:
      - zabbix-server-pgsql
    restart: unless-stopped

  zabbix-proxy-sqlite3:
    image: zabbix/zabbix-proxy-sqlite3:latest
    container_name: zabbix-proxy-sqlite3
    networks:
      zabbix-network:
        ipv4_address: 172.20.240.9
    depends_on:
      - zabbix-server-pgsql
    restart: unless-stopped

  zabbix-agent:
    image: zabbix/zabbix-agent:latest
    container_name: zabbix-agent
    environment:
      ZBX_HOSTNAME: "zabbix-agent"
      ZBX_SERVER_HOST: "zabbix-server-pgsql"
      ZBX_SERVER_PORT: "10051"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro  # para monitoramento de containers, conforme template oficial :contentReference[oaicite:0]{index=0}
    networks:
      zabbix-network:
    depends_on:
      - zabbix-server-pgsql
    restart: unless-stopped