version: '3.8'

services:
  mongo:
    image: mongodb/mongodb-community-server:latest
    container_name: mongo
    volumes:
      - mongo_data:/data/db
    networks:
      - graylog
    restart: unless-stopped

  opensearch:
    image: opensearchproject/opensearch:latest
    container_name: opensearch
    environment:
      - discovery.type=single-node
      - http.host=0.0.0.0
      - transport.host=localhost
      - network.host=0.0.0.0
      - OPENSEARCH_JAVA_OPTS=-Xms1g -Xmx1g
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    mem_limit: 2g
    volumes:
      - os_data:/usr/share/opensearch/data
    networks:
      - graylog
    restart: unless-stopped
    ports:
      - 9200:9200

  graylog:
    image: graylog/graylog:6.3.1
    container_name: graylog
    volumes:
      - graylog_journal:/usr/share/graylog/data/journal
      - /home/monitoramento/graylog:/etc/graylog/server
    environment:
      - GRAYLOG_PASSWORD_SECRET=ZC2L9lDOLfpKPmBp0lmIR-GYW2OXViVBEjJjwSziOMYxVsbK1DuSLjkzDH1qgqHTPXMGFNagHFRmujXDqv5qWrXSnUczV5aA
      - GRAYLOG_ROOT_PASSWORD_SHA2=498ca8869eff866107dfcc0f1a9f0c5f9cdee019faa52ae03f8aecf91665f4e4
      - GRAYLOG_HTTP_EXTERNAL_URI=http://127.0.0.1:9000/
      - GRAYLOG_ELASTICSEARCH_VERSION=7
    entrypoint:
      - /usr/bin/tini
      - -- wait-for-it
      - opensearch:9200
      - --
      - /docker-entrypoint.sh
    networks:
      - graylog
    depends_on:
      - mongo
      - opensearch
    restart: unless-stopped
    ports:
      - 9000:9000
      - 1514:1514
      - 1514:1514/udp
      - 12201:12201
      - 12201:12201/udp

volumes:
  mongo_data:
    driver: local
  os_data:
    driver: local
  graylog_journal:
    driver: local

networks:
  graylog:
    driver: bridge